### ISSUE TITLE
Addition of simple text title to STAMPS art

### ISSUE THREAD

**Issue by mikeinspace** [hydren-crypto/stampchain#87]
Following the method that xchain uses to apply a title in a non-disruptive way after an image pointer, I recommend we use the following approach to add titles to Bitcoin Stamps.

Example from xchain: imgur/i08zbUH.png; FRESHCUT

Method for Stamps: stamp:iVBORw0KGgoAAAANSUhEUg; Title Goes Here

Alternate approach: stamp:iVBORw0KGgoAAAANSUhEUg;Title Goes Here (note that there is no space after semi-colon)

JDog says this method should not disrupt how xchain parses and displays the Base64. Howewer, unless he adds support for it, I don't think the titles will actually show. I can discuss this with him, but I don't feel its a show-stopper even if it isn't implemented.

We should eventually add the "title" to asset pages (directly above the art) on stampchain.io and expose through the API.

We can set a reasonable character length so that people aren't trying to publish paragraphs of text... unless we want them to?

We could even offer a method to add a title to old stamps in the following manner: a broadcast-type txn from the ownership address making reference to the stamp or asset name.

eg: A9364494683859804778 = This is the title

**Comment by hydren-crypto** [comment]
This will currently make for an invalid stamp if tested so we will need to carefully implement.  

The original setup was for having the description or alternative image beofre the stamp like so  "imgur/i08zbUH.png;stamp:iVBORw0KGgoAAAANSUhEUg" or "text goes here;stamp:iVBORw0KGgoAAAANSUhEUg"  which in theory should be working - need to double check this as well. The intention was to just ignore that portion since we won't know what it is (image, text or whatever) - if we know it's always a description then that could be useful to display as text on the website, but if it's an image or something else we would need more checks to wrap that to display the image on the site, etc. 

perhaps a method like ```stamp:iVBORw0KGgoAAAANSUhEUg;desc:"description goes here";coll:"collection name";thumb:"imgur/i08zbUH.png"```  would be the best and then we can easily tell it's a description or any other field we want to implement.. And the parsing wouldn't care what order they are in. It all gets much much more complex with their proposed "multiple stamps in one transaction" and all of the varying mime-type options - which we are currently partially supporting anyway. 

This all needs careful review and coordination.
